# Generated by Django 5.1.6 on 2025-02-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ['-uploaded_at'], 'permissions': [('can_manage', 'Can manage file uploads')]},
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='type',
            field=models.CharField(choices=[('STANDARD_POINTS', 'Standard Points added'), ('REWARD_CLAIM', 'Reward Claim'), ('CREDIT_NOTE_ADJUST', 'Credit Note (dobropis) adjustment'), ('EXTRA_POINTS', 'Extra Points added'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=20),
        ),
    ]
