# Generated by Django 5.1.6 on 2025-02-26 08:18

from django.db import migrations
from pa_bonus.models import create_manager_group_and_permissions


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0002_alter_fileupload_options_remove_user_user_type_and_more'),
    ]

    operations = [
        migrations.RunPython(create_manager_group_and_permissions),
    ]
