# Generated by Django 5.1.6 on 2025-02-26 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0004_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('description', models.TextField()),
                ('total_points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RewardRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('point_cost', models.IntegerField()),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa_bonus.reward')),
                ('reward_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa_bonus.rewardrequest')),
            ],
        ),
    ]
