# Generated by Django 5.1.6 on 2025-03-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0007_pointstransaction_reward_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontract',
            name='extra_goal_12m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercontract',
            name='extra_goal_base',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
