# Generated by Django 5.1.6 on 2025-03-17 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0008_alter_usercontract_extra_goal_12m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstransaction',
            name='file_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transactions', to='pa_bonus.fileupload'),
        ),
    ]
