# Generated by Django 5.1.6 on 2025-03-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0009_pointstransaction_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='processed_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='total_rows',
            field=models.IntegerField(default=0),
        ),
    ]
