# Generated by Django 5.1.6 on 2025-03-28 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0010_fileupload_processed_rows_fileupload_total_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontract',
            name='extra_goal_12m',
        ),
        migrations.RemoveField(
            model_name='usercontract',
            name='extra_goal_base',
        ),
        migrations.CreateModel(
            name='UserContractGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_period_from', models.DateField()),
                ('goal_period_to', models.DateField()),
                ('goal_value', models.IntegerField()),
                ('goal_base', models.IntegerField()),
                ('brands', models.ManyToManyField(to='pa_bonus.brand')),
                ('user_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_goals', to='pa_bonus.usercontract')),
            ],
        ),
    ]
