# Generated by Django 5.1.6 on 2025-04-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0012_emailnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('client_number', models.CharField(db_index=True, max_length=20)),
                ('invoice_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice_type', models.CharField(choices=[('INVOICE', 'Standard Invoice'), ('CREDIT_NOTE', 'Credit Note')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='pa_bonus.fileupload')),
            ],
            options={
                'ordering': ['-invoice_date', 'invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceBrandTurnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_turnovers', to='pa_bonus.brand')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_turnovers', to='pa_bonus.invoice')),
            ],
            options={
                'ordering': ['-invoice__invoice_date', 'brand__name'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client_number', 'invoice_date'], name='pa_bonus_in_client__eae8e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicebrandturnover',
            unique_together={('invoice', 'brand')},
        ),
    ]
