# Generated by Django 5.1.6 on 2025-04-24 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0015_region_user_region_regionrep'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pa_bonus.invoice'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pa_bonus.brand'),
        ),
    ]
