# Generated by Django 5.1.6 on 2025-04-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0016_pointstransaction_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(max_length=10),
        ),
    ]
