# Generated by Django 5.1.6 on 2025-04-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0017_alter_user_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardrequest',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Customer Note'),
        ),
    ]
