# Generated by Django 5.1.6 on 2025-04-29 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0018_rewardrequest_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_DEMAND', 'On Demand'), ('UNAVAILABLE', 'Unavailable')], default='ON_DEMAND', max_length=20),
        ),
        migrations.AlterField(
            model_name='reward',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pa_bonus.brand'),
        ),
    ]
