# Generated by Django 5.1.6 on 2025-04-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0019_reward_availability_alter_reward_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='in_showcase',
            field=models.BooleanField(default=False, help_text='Display this item in the public showcase'),
        ),
    ]
