# Generated by Django 5.1.6 on 2026-02-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0023_alter_usercontractgoal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontractgoal',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='usercontractgoal',
            name='user_contract',
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='type',
            field=models.CharField(choices=[('STANDARD_POINTS', 'Standard Points added'), ('REWARD_CLAIM', 'Reward Claim'), ('CREDIT_NOTE_ADJUST', 'Credit Note (dobropis) adjustment'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=20),
        ),
        migrations.DeleteModel(
            name='GoalEvaluation',
        ),
        migrations.DeleteModel(
            name='UserContractGoal',
        ),
    ]
