# Generated by Django 5.1.6 on 2026-03-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0025_alter_points_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
